# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        logo:
            uri_prefix: /images/stores
            upload_destination: '%kernel.project_dir%/public/images/stores'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        image:
            uri_prefix: /images/stores
            upload_destination: '%kernel.project_dir%/public/images/stores'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer



    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
