controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#    EndroidQrCodeBundle:
#        resource: "@EndroidQrCodeBundle/Controller/"
#        type: annotation
#        prefix: /qrcode
